export const actionCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACT_PAGE: "SET_ALL_CONTACT_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_CHAT_MESSAGE_SOCKET: "ADD_CHAT_MESSAGE_SOCKET",
  SET_MESSAGES_SEARCH: "SET_MESSAGES_SEARCH",
  SET_USERS_CONTACTS: "SET_USERS_CONTACTS",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  SET_CONTACTS_SEARCH: "SET_CONTACTS_SEARCH",

};
